Access error
<?php echo $this->partial('layout/layout.phtml'); ?>

<?php
$msg = 'Application error.';
/** @var \Zend\Http\PhpEnvironment\Response $response */
$response = $this->getHelperPluginManager()->getServiceLocator()->get('response');
if ($response instanceof \Zend\Http\PhpEnvironment\Response) {
    if ($response->getStatusCode() == 401) {
        $msg = 'Access Denied';
    }
}
?>
<div class="page-content">
    <div id="access_denied" style="text-align: center; margin: 100px 25px; 100px">
        Access Denied to this page
        <p><a href="/">Back</a></p>
    </div>
</div>

