<?php echo $this->partial('application/includes/flash_message.phtml'); ?>
<?php echo $this->partial('application/includes/delete_modal.phtml'); ?>

<div class="mdl-grid">
<!--    <div class="mdl-cell mdl-cell--2-col">All Issues</div>-->
    <div class="mdl-cell mdl-cell--6-col">
        <ol class="demo-list-item ">
        <?php foreach ($boards as $board): ?>
                <li class="mdl-list__item-text-body">

                     <div class="mdl-list__item-primary-content">
                        <div class="mdl-list__item-secondary-action">
                            <a  href="/boards/details/<?php echo $board->getId() ?>">
                        Board name:<?php echo $board->getTitle() ?></a></div>
                        <div class="mdl-list__item-text-body">Administrators:<?php if($board->getAdministrator()):
                         echo $board->getAdministrator()->getFirstName(); endif; ?>
                        </div>
                            <div class="mdl-list__item-text-body">Project:<?php  echo $board->getProject()->getName() ?>
                        </div>
                   

                    <!--                    <a class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab"-->
                    <!--                       href="/issues/create/-->
                    <?php //echo $issue->getId() ?><!--"> <i class="material-icons">mode_edit</i>-->
                    <!--                    </a>-->
                    <!---->
                    <!--                    <a class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab show-dialog "-->
                    <!--                       data-url="/issues/delete/--><?php //echo $issue->getId() ?><!--"><i-->
                    <!--                            class="material-icons">delete</i> </a>-->
                </li>
        <?php endforeach; ?>
        </ol>
        <div class="mdl-cell mdl-cell--2-col addButton">
            <a class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored " href="/boards/create/">
                <i class="material-icons">add</i>
            </a>
            <?php //echo $paginator; ?>
        </div>
    </div>
