<div class="mdl-dialog dialogAccount" id="dialogAccountCompany">
    <h5 class="dialogTitle">Choose company</h5>
    <div class="mdl-dialog__content account" data-id="<?php echo $user->getCompanyAccount() ?>">
        <?php if ($usersCompanies): ?>
            <div class="form-group ">
                <?php foreach ($usersCompanies as $company): ?>
                    <input name="role" type="radio" class="mdl-radio__button" value="<?php echo $company->getId() ?>"> <label for="cbox1"><?php echo $company->getName() ?></label><br/>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
    <div class="mdl-dialog__actions">
        <a href="#" type="button" class="mdl-button mdl-js-button mdl-button--raised modal-action-account-agree">Agree</a>
        <button type="button" class="mdl-button button-close-account-disagree">Disagree</button>
    </div>
</div>
<div class="mdl-dialog dialogAccount" id="dialogAccountUser">
    <h5 class="dialogTitle">You switch to user mode</h5>
    <div class="mdl-dialog__actions">
        <a href="#" type="button" class="mdl-button mdl-js-button mdl-button--raised actionAccountUser">Agree</a>
    </div>
</div>

<script>
    $(function () {
        if ($('.account').data('id') != "") {
            $('.showCompanies ').addClass('is-checked');
        }
        $('#showCompanies :checkbox').change(function () {
            if ($(this).attr('checked', true)) {
                if (!$.cookie("companyAccount")) {
                    $("#dialogAccountCompany").show();
                }
                else {
                    $.removeCookie('companyAccount');
                    $("#dialogAccountUser").show();
                }
            }
        });
        $('.actionAccountUser').click(function () {
            $('.showCompanies ').removeClass('is-checked');
            $("#dialogAccountUser").hide();
            $.removeCookie('companyAccount');
            $.ajax({
                type: "POST",
                url: "/company/index",
                data: 'idCompany=' + null,
                dataType: "html",
                success: function () {
                }
            });
        });
        $('.modal-action-account-agree').click(function () {
            $.cookie('companyAccount', "1");
            $('.showCompanies ').addClass('is-checked');
            $.ajax({
                type: "POST",
                url: "/company/index",
                data: 'idCompany=' + $("input:checked").val(),
                dataType: "html",
                success: function () {
                }
            });
            $("#dialogAccountCompany").hide();
        });
        $('.button-close-account-disagree').click(function () {
            $('.showCompanies ').removeClass('is-checked');
            $("#dialogAccountCompany").hide();
        });
    });
</script>
