<?php echo $this->partial('application/includes/flash_message.phtml'); ?>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--12col project" data-id="<?php echo $project->getId(); ?>">
                <ul class="demo-list-three">
                    <?php if (!empty($permissions)): ?>
                        <li class="mdl-list__item">User list</li>
                        <table class="mdl-data-table mdl-js-data-table ">
                            <tbody>
                            <tr>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th></th>
                            </tr>
                            <?php foreach ($permissions as $permission): ?>
                                <tr>
                                    <td><?php echo $permission->getUser()->getFirstName(); ?></td>
                                    <td><?php echo $permission->getUser()->getLastName(); ?></td>
                                    <td><?php echo $permission->getUser()->getEmail(); ?></td>
                                    <td>
                                        <div class="mdl-cell mdl-cell--4-col permission ">
                                            <button class="mdl-button mdl-js-button mdl-button--raised showPermission"  data-id="<?php echo $permission->getUser()->getId(); ?>">
                                                Edit Permission
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php endif; ?>
                </ul>
                <a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"  href="/projects/invite/<?php echo $project->getId(); ?>">Add User to Project</a>
            </div>
        </div>
    </div>
</div>
<dialog class="mdl-dialog  mdl-cell--3-col" id="dialogAccount">
    <div class="mdl-dialog__content dialogAccount" >
        <h5 class="dialogTitle">Permission to Project</h5>
        <div class="permissionForm" ></div>
        <a href="#" type="button" class="mdl-button mdl-js-button mdl-button--raised modal-actionAccount">Agree</a>
        <button type="button" class="mdl-button buttonCloseAccount">Disagree</button>
    </div>
</dialog>
<script>
    $(function () {
        $('.showPermission').click(function () {
            var id = $(this).data('id');
            var project_id = $('.project').data('id');
            $.ajax({
                type: "POST",
                url: "/projects/users/" + project_id,
                data: 'user_id='+id,
                dataType: "html",
                success: function (data) {
                    console.log("1111");
                    $('.permissionForm').html(data);
                    console.log(data);
                    dialogAccount =  document.getElementById('dialogAccount');
                    dialogAccount.showModal();
                }
            });
        });
        $('.modal-actionAccount').click(function () {
            var idTmp = $(this).attr('id');
            var id = idTmp.substring(idTmp.lastIndexOf('-') + 1);

            projectIdTmp =  $('#project_id').val();
            var projectId = $(projectIdTmp).attr('value');
//            var container = $(this).closest('#form-' + id);
//            var container = $(this).closest('.permissionForm');
            var $form = $(this).closest.find('form');
//            var $form =  $(this).parent().find('> form');
            var data = $form.serialize();
            console.log($form);
            console.log(data);
            $.ajax({
                type: "POST",
                url: "/projects/users/" + projectId,
                data: data,
                dataType: "html",
                success: function (data) {
                }
            });
            dialogAccount.close();
        });
        $('.buttonCloseAccount').click(function () {
            dialogAccount.close();
        });
    });
</script>


